server:
  port: 8090

spring:
  application:
    name: section-2
  jpa:
    hibernate:
      ddl-auto: create-drop # This does not use in production
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
